# Generated by Django 5.2.1 on 2025-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_cupon_fecha_fin_alter_cupon_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cupon',
        ),
        migrations.RemoveField(
            model_name='estadopedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='estadopedido',
            name='usuario_cambio',
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='costo_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='impuestos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pais_envio',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia'), ('contrareembolso', 'Contra Reembolso')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Cupon',
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='imagen_producto',
        ),
    ]
